// Eligibility rules as data. Dollar figures are conservative published
// maximums for 2025-26 and are ESTIMATES — every card links to the official
// source and the UI tells users to verify. confidence: 'high' = clear-cut
// published criteria; 'medium' = real eligibility has nuances the wizard
// can't fully capture.

export const RULES = [
  {
    id: 'pell-grant',
    name: 'Federal Pell Grant',
    org: 'U.S. Dept. of Education',
    estimatedValue: { min: 700, max: 7395, display: 'up to $7,395/yr' },
    cash: true,
    confidence: 'high',
    why: 'Grant money for school you never pay back.',
    howToApply: 'File the FAFSA at StudentAid.gov — Pell is automatic from there.',
    link: 'https://studentaid.gov/understand-aid/types/grants/pell',
    criteria: [
      { field: 'enrollment', op: 'in', value: ['full', 'part'], label: 'enrollment status' },
      { field: 'income', op: 'in', value: ['under30k', '30to60k'], label: 'household income' },
    ],
  },
  {
    id: 'ny-tap',
    name: 'NY Tuition Assistance Program (TAP)',
    org: 'New York State',
    estimatedValue: { min: 500, max: 5665, display: 'up to $5,665/yr' },
    cash: true,
    confidence: 'high',
    why: 'NY State grant money for tuition — separate from and on top of Pell.',
    howToApply: 'Apply at hesc.ny.gov after filing your FAFSA.',
    link: 'https://www.hesc.ny.gov/find-aid/nys-grants-scholarships/tuition-assistance-program',
    criteria: [
      { field: 'state', op: 'eq', value: 'NY', label: 'NY residency' },
      { field: 'enrollment', op: 'eq', value: 'full', label: 'full-time enrollment' },
      { field: 'income', op: 'in', value: ['under30k', '30to60k'], label: 'household income' },
    ],
  },
  {
    id: 'excelsior',
    name: 'Excelsior Scholarship',
    org: 'New York State',
    estimatedValue: { min: 0, max: 7000, display: 'covers remaining tuition' },
    cash: true,
    confidence: 'medium',
    why: 'Covers whatever CUNY/SUNY tuition is left after Pell and TAP.',
    howToApply: 'Apply at hesc.ny.gov (deadline is usually late spring). Requires 30 credits/year.',
    link: 'https://www.hesc.ny.gov/find-aid/nys-grants-scholarships/excelsior-scholarship',
    criteria: [
      { field: 'state', op: 'eq', value: 'NY', label: 'NY residency' },
      { field: 'enrollment', op: 'eq', value: 'full', label: 'full-time enrollment' },
      { field: 'income', op: 'in', value: ['under30k', '30to60k', '60to125k'], label: 'household income' },
    ],
  },
  {
    id: 'federal-work-study',
    name: 'Federal Work-Study',
    org: 'U.S. Dept. of Education',
    estimatedValue: { min: 0, max: 2400, display: '~$2,000+/yr in campus wages' },
    cash: true,
    confidence: 'medium',
    why: 'Paid part-time campus jobs reserved for students with financial need.',
    howToApply: 'Check the work-study box when filing your FAFSA, then ask your financial aid office.',
    link: 'https://studentaid.gov/understand-aid/types/work-study',
    criteria: [
      { field: 'enrollment', op: 'in', value: ['full', 'part'], label: 'enrollment status' },
      { field: 'income', op: 'in', value: ['under30k', '30to60k'], label: 'household income' },
    ],
  },
  {
    id: 'snap',
    name: 'SNAP (Food Stamps)',
    org: 'Federal / State',
    estimatedValue: { min: 0, max: 3500, display: 'up to ~$290/mo for groceries' },
    cash: true,
    confidence: 'medium',
    why: 'Monthly grocery money. Students qualify via work-study, 20hr/wk work, or other exemptions.',
    howToApply: 'Apply through your state (NY: mybenefits.ny.gov). CUNY Single Stop can help you apply.',
    link: 'https://www.fns.usda.gov/snap/students',
    criteria: [
      { field: 'income', op: 'eq', value: 'under30k', label: 'household income' },
    ],
  },
  {
    id: 'medicaid',
    name: 'Medicaid',
    org: 'Federal / State',
    estimatedValue: { min: 0, max: 5000, display: 'free health coverage' },
    cash: true,
    confidence: 'medium',
    why: 'Free or near-free health insurance if your income qualifies.',
    howToApply: 'NY: apply at nystateofhealth.ny.gov. Other states: healthcare.gov.',
    link: 'https://www.medicaid.gov/',
    criteria: [
      { field: 'income', op: 'eq', value: 'under30k', label: 'household income' },
      { field: 'insurance', op: 'eq', value: false, label: 'insurance status' },
    ],
  },
  {
    id: 'fair-fares',
    name: 'Fair Fares NYC',
    org: 'City of New York',
    estimatedValue: { min: 0, max: 700, display: 'half-price subway & bus rides' },
    cash: true,
    confidence: 'medium',
    why: 'NYC residents with lower incomes get 50% off OMNI/MetroCard fares.',
    howToApply: 'Apply at nyc.gov/fairfares with proof of NYC residency and income.',
    link: 'https://www.nyc.gov/site/fairfares/index.page',
    criteria: [
      { field: 'state', op: 'eq', value: 'NY', label: 'NY residency' },
      { field: 'commute', op: 'eq', value: true, label: 'NYC transit use' },
      { field: 'income', op: 'eq', value: 'under30k', label: 'household income' },
    ],
  },
  {
    id: 'campus-pantry',
    name: 'CSI Food Pantry',
    org: 'College of Staten Island',
    estimatedValue: { min: 240, max: 600, display: 'free groceries on campus' },
    cash: true,
    confidence: 'high',
    why: 'CSI, like every CUNY campus, runs a free food pantry for enrolled students. No income proof needed.',
    howToApply: 'Ask CSI Student Services about the campus food pantry — usually you just show your student ID. The CUNY pantry list has current details.',
    link: 'https://www.cuny.edu/current-students/student-affairs/student-services/food-pantries/',
    criteria: [
      { field: 'enrollment', op: 'in', value: ['full', 'part'], label: 'enrollment status' },
      { field: 'food', op: 'in', value: ['often', 'sometimes'], label: 'food need' },
    ],
  },
  {
    id: 'emergency-aid',
    name: 'Emergency Student Grants',
    org: 'College of Staten Island',
    estimatedValue: { min: 0, max: 1500, display: 'one-time crisis grants' },
    cash: true,
    confidence: 'medium',
    why: 'Many colleges quietly offer one-time grants for rent, food, or medical emergencies.',
    howToApply: 'Email CSI Financial Aid (financialaid@csi.cuny.edu) or the Dean of Students and ask about "emergency grants".',
    link: 'https://studentaid.gov/resources/prepare-for-college/students/heerf',
    criteria: [
      { field: 'enrollment', op: 'in', value: ['full', 'part'], label: 'enrollment status' },
      { field: 'food', op: 'eq', value: 'often', label: 'hardship level' },
    ],
  },
  {
    id: 'single-stop',
    name: 'CUNY Single Stop',
    org: 'CUNY',
    estimatedValue: { min: 0, max: 0, display: 'free benefits screening, legal aid & tax prep' },
    cash: false,
    confidence: 'high',
    why: 'A free CUNY office that screens you for ALL public benefits and files the paperwork with you — available to CSI students.',
    howToApply: 'Walk into the Single Stop office on your campus or book online.',
    link: 'https://www.cuny.edu/current-students/student-affairs/student-services/single-stop/',
    criteria: [
      { field: 'cuny', op: 'eq', value: true, label: 'CUNY enrollment' },
    ],
  },
  {
    id: 'github-student-pack',
    name: 'GitHub Student Developer Pack',
    org: 'GitHub Education',
    estimatedValue: { min: 0, max: 0, display: 'free dev tools & cloud credits' },
    cash: false,
    confidence: 'high',
    why: 'Free GitHub Pro, cloud credits, domains, and dozens of paid dev tools while enrolled.',
    howToApply: 'Apply at education.github.com/pack with your .edu email.',
    link: 'https://education.github.com/pack',
    criteria: [
      { field: 'enrollment', op: 'in', value: ['full', 'part'], label: 'enrollment status' },
    ],
  },
  {
    id: 'cuny-reconnect',
    name: 'CUNY Reconnect',
    org: 'CUNY',
    estimatedValue: { min: 0, max: 0, display: 'free re-enrollment help & aid navigation' },
    cash: false,
    confidence: 'high',
    why: 'Helps adults 24+ who left college return and finish their degree, including clearing old balances.',
    howToApply: 'Sign up at cuny.edu/reconnect — an advisor contacts you.',
    link: 'https://www.cuny.edu/reconnect/',
    criteria: [
      { field: 'age', op: 'in', value: ['24to25', '26plus'], label: 'age' },
      { field: 'enrollment', op: 'eq', value: 'none', label: 'enrollment status' },
      { field: 'state', op: 'eq', value: 'NY', label: 'NY residency' },
    ],
  },
]
